import { createContext, useContext } from 'react'
import zhHans from './zh-Hans'

// Lightweight UI translation — no framework. The KEY is the English source
// string, so anything not wrapped in t() (or not yet in the catalogue) simply
// renders in English. Scoped, on purpose, to the supply / inventory pages a
// Chinese-only staff account can reach; the rest of the app stays English.
//
// The catalogue is generated by scripts/i18n-translate.mjs (DeepSeek) and then
// hand-corrected in place; that script only tops up missing keys, so edits
// survive a re-run.

const CATALOGUES = { 'zh-Hans': zhHans }

export const UI_LANGS = [
  { code: 'en', label: 'English' },
  { code: 'zh-Hans', label: '简体中文' },
]
export const isUiLang = (c) => UI_LANGS.some((l) => l.code === c)

export const UiLangContext = createContext('en')
export const useUiLang = () => useContext(UiLangContext)

// translate('zh-Hans', 'Save', { n: 3 })  ->  '保存' / 'Save {n}' with {n}→3
export function translate(lang, key, vars) {
  const dict = CATALOGUES[lang]
  let s = (dict && Object.prototype.hasOwnProperty.call(dict, key) && dict[key]) || key
  if (vars) {
    for (const k of Object.keys(vars)) s = s.split(`{${k}}`).join(String(vars[k]))
  }
  return s
}

// const t = useT();  t('Add supplier')
export function useT() {
  const lang = useUiLang()
  return (key, vars) => translate(lang, key, vars)
}
