// Simplified-Chinese UI strings, keyed by the English source string.
// Generated by scripts/i18n-translate.mjs (DeepSeek) and hand-corrected in
// place — a re-run only adds missing keys, so corrections are kept.
// Anything not listed here renders in English.
export default {
}
