import { useState, useEffect } from 'react'
import { youtubeId } from '../constants'

// A hardcoded 16:9 box was forcing every video — including vertical YouTube
// Shorts — into a landscape iframe frame. YouTube's own player doesn't
// centre a portrait video inside a too-wide frame, it renders it pinned to
// one side with dead black space filling the rest (reported live,
// 2026-08-21). Fixed by sizing the box (and centering it as a column, not
// just cropping content within a full-width box) to the video's REAL
// aspect ratio instead of assuming landscape.
//
// First attempt used YouTube's oEmbed endpoint to detect the real aspect
// ratio — dropped (still live, 2026-08-21) after it reported landscape-ish
// dimensions for a video that was visibly portrait, a known unreliability
// of that endpoint specifically for Shorts. Now uses two signals that are
// actually trustworthy: the `/shorts/` URL itself (an instant, free,
// deterministic signal), and — once maxresdefault.jpg has actually loaded
// — that image's own real pixel dimensions, since it's generated per-video
// at its true size (see THUMB_SIZES below for why this only holds for
// maxresdefault, not the smaller fallback sizes).
const isLikelyShort = url => /\/shorts\//i.test(url || '')

// Landscape videos fill the available width like before; a portrait video
// is capped to a sensible column width and centred (mx-auto) rather than
// stretched edge-to-edge at some absurd height.
const MAX_PORTRAIT_WIDTH = 360

// hqdefault.jpg (and sddefault.jpg below it) is always generated by
// YouTube as a fixed legacy landscape frame — for a portrait video the
// black bars are baked into the JPEG's actual pixels, not a CSS artifact,
// so no amount of object-fit/cropping removes them, AND its reported
// naturalWidth/naturalHeight is the padded landscape size, not the real
// video's — not a usable orientation signal. maxresdefault.jpg is the one
// size generated per-video at its real dimensions (unpadded for most
// Shorts), which is why it's tried first and why ONLY its naturalWidth/
// naturalHeight (thumbLevel === 0 below) is trusted for sizing the box.
// It doesn't exist for every video (real 404 — confirmed live via curl),
// so there's still a fallback chain down to hqdefault, which is the one
// size YouTube guarantees for any indexed video.
const THUMB_SIZES = ['maxresdefault', 'sddefault', 'hqdefault']

// Lazy YouTube embed (facade pattern). Until the user clicks play we show only a
// lightweight thumbnail + play button — the heavy YouTube iframe (which pulls in
// ~1-2MB of player JS) is mounted ONLY after the click. Renders nothing when
// `url` isn't a valid YouTube link, so callers can drop it in unconditionally.
export default function VideoEmbed({ url, title = 'Product video', className = '' }) {
  const id = youtubeId(url)
  const [playing, setPlaying] = useState(false)
  // height/width fraction — 9/16 = landscape default, 16/9 = portrait guess
  // for a /shorts/ url. Refined once maxresdefault.jpg actually loads (see
  // handleThumbLoad) for every OTHER portrait video too — one linked via a
  // plain /watch?v= url, where the URL itself gives no hint.
  const [ratio, setRatio] = useState(() => (isLikelyShort(url) ? 16 / 9 : 9 / 16))
  const [thumbLevel, setThumbLevel] = useState(0)

  // Same instance can be reused for a DIFFERENT id (e.g. React reusing a
  // list slot by index while an admin reorders/edits a product's video
  // list) — reset both derived-from-the-old-video states rather than
  // carrying stale ratio/fallback-level over onto the new one.
  useEffect(() => {
    setRatio(isLikelyShort(url) ? 16 / 9 : 9 / 16)
    setThumbLevel(0)
  }, [id])

  if (!id) return null
  const isPortrait = ratio > 1

  // Only maxresdefault.jpg's own pixel dimensions are trustworthy for
  // orientation (see THUMB_SIZES) — a fallback to sddefault/hqdefault means
  // this video has no maxresdefault, so its dimensions are ALWAYS the
  // padded legacy landscape size regardless of the real video, and must be
  // ignored rather than used to (wrongly) flip the box back to landscape.
  const handleThumbLoad = e => {
    if (thumbLevel !== 0) return
    const { naturalWidth: w, naturalHeight: h } = e.target
    if (w && h) setRatio(h / w)
  }

  return (
    <div className={className}>
      <div
        className="relative overflow-hidden rounded-none bg-black"
        style={{
          paddingBottom: `${ratio * 100}%`,
          width: isPortrait ? `min(100%, ${MAX_PORTRAIT_WIDTH}px)` : '100%',
          marginInline: isPortrait ? 'auto' : undefined,
        }}
      >
        {playing ? (
          <iframe
            src={`https://www.youtube.com/embed/${id}?autoplay=1`}
            title={title}
            className="absolute inset-0 w-full h-full"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowFullScreen
          />
        ) : (
          <button
            type="button"
            onClick={() => setPlaying(true)}
            aria-label={`Play ${title}`}
            className="absolute inset-0 w-full h-full group cursor-pointer"
          >
            <img
              src={`https://img.youtube.com/vi/${id}/${THUMB_SIZES[thumbLevel]}.jpg`}
              onError={() => setThumbLevel(l => Math.min(l + 1, THUMB_SIZES.length - 1))}
              onLoad={handleThumbLoad}
              alt={title}
              loading="lazy"
              className="absolute inset-0 w-full h-full object-cover"
            />
            <span className="absolute inset-0 flex items-center justify-center bg-black/20 group-hover:bg-black/30 transition-colors">
              <span className="flex items-center justify-center w-16 h-11 rounded-none bg-red-600 group-hover:bg-red-700 transition-colors shadow-lg">
                <svg viewBox="0 0 24 24" width="26" height="26" fill="white" aria-hidden="true">
                  <path d="M8 5v14l11-7z" />
                </svg>
              </span>
            </span>
          </button>
        )}
      </div>
    </div>
  )
}
